twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        network: '%navcoin.network%'
        explorer:
            api:
                url: '%explorer.api.url%'

    exception_controller: null